version: '3.8'

services:
  healthcare-frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env 